### ISSUE TITLE
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by XiaoBai-collab** [researchmm/TracKit#25]
I encountered an error when I ran the test_siamdw file:
python tracking/test_siamdw.py --arch Ocean --resume snapshot/siamdw_res22w.pth --dataset VOT2019
Traceback (most recent call last):
  File "tracking/test_siamdw.py", line 13, in <module>
    import models.models as models
  File "/home/xiaobai/PycharmProjects/ObjectTrackingCode/DLCode/TracKit-master/tracking/../lib/models/models.py", line 14, in <module>
    from .connect import box_tower, AdjustLayer, AlignHead, Corr_Up, MultiDiCorr, OceanCorr
  File "/home/xiaobai/PycharmProjects/ObjectTrackingCode/DLCode/TracKit-master/tracking/../lib/models/connect.py", line 9, in <module>
    from .dcn import DeformConv, DeformConvPack
  File "/home/xiaobai/PycharmProjects/ObjectTrackingCode/DLCode/TracKit-master/tracking/../lib/models/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/xiaobai/PycharmProjects/ObjectTrackingCode/DLCode/TracKit-master/tracking/../lib/models/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory.

Could you tall me how can i solve it? Thanks a lot.

**Comment by XiaoBai-collab** [comment]
I'm sorry I didn't notice the answer to the first question. I'll try again.
