### ISSUE TITLE
NameError: name 'reloadTRT' is not defined

### ISSUE THREAD

**Issue by soltkreig** [researchmm/TracKit#78]
Hey, I'm trying to run_video.py on my video and use TRT but get this error.
~/TracKit$ python tracking/run_video.py --arch OceanTRT --video videos/1.mp4
===> init Siamese <====
tensorrt toy model: not loading checkpoint
===> load model from TRT <===
===> please ignore the warning information of TRT <===
===> We only provide a toy demo for TensorRT. There are some operations are not supported well.<===
===> If you wang to test on benchmark, please us Pytorch version. <===
===> The tensorrt code will be contingously optimized (with the updating of official TensorRT.)<===
Traceback (most recent call last):
  File "tracking/run_video.py", line 231, in <module>
    main()
  File "tracking/run_video.py", line 211, in main
    trtNet = reloadTRT()
NameError: name 'reloadTRT' is not defined

**Comment by soltkreig** [comment]
I've got this one:
(TracKit):~/TracKit$ python tracking/test_ocean.py --arch OceanTRT --video videos/1.mp4
Traceback (most recent call last):
  File "tracking/test_ocean.py", line 29, in <module>
    from lib.core.eval_otb import eval_auc_tune
ModuleNotFoundError: No module named 'lib.core'

**Comment by soltkreig** [comment]
I run in environment "TracKit", I didn't create another one like "OceanTRT"

**Comment by soltkreig** [comment]
(TracKit) kfour@kfour:~/TensorRT-7.0.0.11/python$ pip install tensorrt-7.0.0.11-cp37-none-linux_x86_64.whl

Processing ./tensorrt-7.0.0.11-cp37-none-linux_x86_64.whl
tensorrt is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

**Comment by soltkreig** [comment]
I just found this one:
https://forums.developer.nvidia.com/t/attributeerror-nonetype-object-has-no-attribute-create-execution-context/110199/5

**Comment by JudasDie** [comment]
> I googled else and understood I need to rebuild the engine for my GPU, do you have any ideas how to do it? I've found that: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#build_engine_python

Have you found the solution?

**Comment by Stoooner** [comment]
大佬啊，我也遇到了AttributeError: 'NoneType' object has no attribute 'create_execution_context'这个问题，已经跟install和install_trt里要求的安装成了一模一样了，但是还是报了这个错误，完全不知道哪里错了，只能定位到test_ocean.py里t_bk.load_state_dict(torch.load(t_bk_path))这句开始错了，应该是加载的这个trt文件有问题吧？是不是大佬传上去的trt模型有问题呢？

**Comment by penghouwen** [comment]
pls refer to our most recent work https://github.com/researchmm/Stark and https://github.com/researchmm/LightTrack
