### ISSUE TITLE
train的时候出现问题

### ISSUE THREAD

**Issue by fangh026** [researchmm/TracKit#88]
Traceback (most recent call last):
  File "./tracking/train_ocean.py", line 259, in <module>
    main()
  File "./tracking/train_ocean.py", line 199, in main
    model = models.__dict__[config.OCEAN.TRAIN.MODEL](align=True).cuda()  # build model
  File "/home/bpc/fh/TracKit/tracking/../lib/models/models.py", line 30, in __init__
    self.align_head = AlignHead(256, 256) if align else None
  File "/home/bpc/fh/TracKit/tracking/../lib/models/connect.py", line 210, in __init__
    self.rpn_conv = AdaptiveConv(in_channels, feat_channels)
  File "/home/bpc/fh/TracKit/tracking/../lib/models/connect.py", line 191, in __init__
    self.conv = DeformConv(in_channels, out_channels, 3, padding=1)
NameError: name 'DeformConv' is not defined

我重新安装了setup.py几次依旧是在个问题

**Comment by SparkTempest** [comment]
同问，题主解决了吗？

**Comment by SparkTempest** [comment]
> Traceback (most recent call last): File "./tracking/train_ocean.py", line 259, in main() File "./tracking/train_ocean.py", line 199, in main model = models.**dict**[config.OCEAN.TRAIN.MODEL](align=True).cuda() # build model File "/home/bpc/fh/TracKit/tracking/../lib/models/models.py", line 30, in **init** self.align_head = AlignHead(256, 256) if align else None File "/home/bpc/fh/TracKit/tracking/../lib/models/connect.py", line 210, in **init** self.rpn_conv = AdaptiveConv(in_channels, feat_channels) File "/home/bpc/fh/TracKit/tracking/../lib/models/connect.py", line 191, in **init** self.conv = DeformConv(in_channels, out_channels, 3, padding=1) NameError: name 'DeformConv' is not defined
> 
> 我重新安装了setup.py几次依旧是在个问题

同问，题主解决了吗？
